app:
  env:
    local:
      port: 3000
secrets:
  foo:
    namespaced: false
  bar:
    namespaced: false
  mix:
    namespaced: true
services:
  demo1:
    id: ms-demo1
    env:
      local:
        port: 3001
  demo2:
    id: ms-demo2
    env:
      local:
        port: 3002